import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Sidebar from "@/components/sidebar/sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body style={{ fontFamily: 'Outfit, sans-serif', margin: 0 }} className="antialiased">
        <div style={{ display: 'flex', flexDirection: 'column', height: '100vh' }}>
          <div style={{ backgroundColor: 'black', position: 'sticky', top: '0', zIndex: '1000' }}>
            <Navbar />
          </div>
          <div style={{ display: 'flex', flex: '1', marginTop: '0px', position: 'sticky' }}> {/* Add marginTop to create space below navbar */}
            <div>
              <Sidebar />
            </div>
            <div style={{ flex: 1, padding: '20px' }}>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
